### ISSUE TITLE
Fix possible key encryption issues

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/openrauseraccounts#23]
The authentication does not work with the prototype OpenRA/OpenRA branch in my local development environment. We should make sure that this is not caused by an issue in the extension (would need to look [here](https://github.com/lawando/OpenRAUserAccounts/blob/master/ucp/useraccounts_module.php#L70) and if the encryption methods are used equally (i.e. sha1 the unstripped plaintext public key without salt). I'm also very confused that the sha1 of a public key is not identical to the output of web sha1 generators when using the same public key.

**Comment by pchote** [comment]
I am unable to reproduce this issue, so this may be related to something in your local config.

**Comment by pchote** [comment]
> the sha1 of a public key is not identical to the output of web sha1 generators when using the same public key.

I also cannot reproduce this.

**Comment by matjaeck** [comment]
Ok, good to know. Closing after we tested it on the real server.

**Comment by matjaeck** [comment]
Fixed in OpenRA/OpenRA#15333.
