### ISSUE TITLE
General review comments

### ISSUE THREAD

**Issue by pchote** [OpenRA/openrauseraccounts#34]
/controller/main.php: Return error messages as a response instead of echoing and exiting.

/core/core.php: get_badge_sql function shares no code between the userid / fingerprint cases, and will behave badly if neither are given.  Split this into two different functions instead.

/ucp/useraccounts_module.php: `empty($markedbadges) ? $delete_sql = '' : ' AND ' . $this->db->sql_in_set('badge_id', $markedbadges, true);` looks bogus.  Did you mean delete_sql = empty($markedbadges) ?  '' : ' AND ' ...`? If not, write this as a proper if statement.

/language/en/*.php: Why do these filenames end with an underscore?

**Comment by matjaeck** [comment]
These points have been addressed in the referenced pr.
